---
- name: Delete user Ansible
  hosts: all
  become: true
  tasks:
    - name: Task 1 - Delete user ansible
      ansible.builtin.user:
        name: ansible
        state: absent
        
    - name: Task 2 - Delete group Admins
      ansible.builtin.group:
        name: admins
        state: absent

        
        
        
        
